UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/fLgqSsR.jpg' WHERE
  MOVIE_ID = 1;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/CDTXtPS.jpg' WHERE
  MOVIE_ID = 2;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/ZAlO2Eq.jpg' WHERE
  MOVIE_ID = 3;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/jmQenR4.jpg' WHERE
  MOVIE_ID = 4;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/bWBzsjD.jpg' WHERE
  MOVIE_ID = 5;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/ev6eRey.jpg' WHERE
  MOVIE_ID = 6;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/SltvaDv.jpg' WHERE
  MOVIE_ID = 7;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/sY6KAhj.jpg' WHERE
  MOVIE_ID = 8;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/ldKX4wu.jpg' WHERE
  MOVIE_ID = 9;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/a7wq5iQ.jpg' WHERE
  MOVIE_ID = 10;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/BQkqHGb.jpg' WHERE
  MOVIE_ID = 11;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/9iLXaRR.jpg' WHERE
  MOVIE_ID = 12;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/RbvCZ09.jpg' WHERE
  MOVIE_ID = 13;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/VmO464D.jpg' WHERE
  MOVIE_ID = 14;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/dT1bPzC.jpg' WHERE
  MOVIE_ID = 15;
UPDATE MOVIES SET MOVIE_IMAGE = 'https://i.imgur.com/gfdSlRZ.jpg' WHERE
  MOVIE_ID = 16;